version: "3.3"

services:

  nginx:
    image: dbogatov/status-site:nginx-master
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - internal

  docs:
    image: dbogatov/status-site:docs-master
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - internal

  web:
    image: dbogatov/status-site:web-master
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - internal
    secrets:
      - appsettings.production.yml

  ping:
    image: dbogatov/status-site:ping-master
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - internal
  
  daemons:
    image: dbogatov/status-site:daemons-master
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - internal
    secrets:
      - appsettings.production.yml

  database:
    image: postgres:9.6.3-alpine
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_DB: statussite
      POSTGRES_USER: statususer
      POSTGRES_PASSWORD: relyOn1InternalSwarmNetwork
    networks:
      - internal

networks:
  internal:
    driver: overlay

secrets:
  appsettings.production.yml:
    external: true
