version: '2'
services:
  nginx:
    image: dbogatov/status-site:nginx-${DOTNET_TAG}
    ports:
      - 5555:5555
    links:
      - "web:web"
      - "docs:docs"
    depends_on:
      - web
      - docs
  docs:
    image: dbogatov/status-site:docs-${DOTNET_TAG}
    ports:
      - 5556:80
    restart: on-failure
  web:
    image: dbogatov/status-site:web-${DOTNET_TAG}
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - postgres
    links:
      - "postgres:database"
    volumes:
      - ./appsettings.yml:/srv/appsettings.production.yml
    restart: on-failure
  ping:
    image: dbogatov/status-site:ping-${DOTNET_TAG}
    ports:
      - 8888:8888
    restart: on-failure
  daemons:
    image: dbogatov/status-site:daemons-${DOTNET_TAG}
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - postgres
    links:
      - "postgres:database"
      - "ping:ping"
    volumes:
      - ./appsettings.yml:/srv/appsettings.production.yml
    restart: on-failure
  postgres:
    image: postgres:9.6.3-alpine
    environment: # define connection credentials to be used in app
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
