---
apiVersion: extensions/v1beta1 
kind: Deployment 
metadata:
  name: __NAME__
  namespace: status-site 
  labels:
    application: __NAME__
spec:
  replicas: 1
  selector:
    matchLabels:
      application: __NAME__
  template:
    metadata:
      labels:
        application: __NAME__
    spec:
      containers:
        - name: __NAME__
          image: __IMAGE__
          imagePullPolicy: Always
          volumeMounts:
            - name: database-persistent-storage
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_DB
              value: "statussite"
            - name: POSTGRES_USER
              value: "statususer"
            - name: POSTGRES_PASSWORD
              value: "relyOn1InternalSwarmNetwork"
      volumes:
        - name: database-persistent-storage
          persistentVolumeClaim:
            claimName: database-pv-claim
