---
apiVersion: v1
kind: Service
metadata:
  name: __NAME__ 
  namespace: status-site 
  labels:
    application: __NAME__
spec:
  selector:
    application: __NAME__
  ports:
  - port: __PORT__
    targetPort: __PORT__ 
