CompanyName: "Your company"
Secrets:
  ApiKey: "needs-to-be-set"
  AdminPassword: "password"
  ReCaptcha:
    Enabled: false
    SiteKey: "needs-to-be-set"
    SecretKey: "needs-to-be-set"
  Email:
    Enabled: false
  Slack:
    Enabled: false
    WebHook: "needs-to-be-set"
ServiceManager:
  DemoService:
    Enabled: true
  CleanService:
    MaxAge: 259200
