Secrets:
  ApiKey: "SDJFSLDKJFS"
  AdminPassword: "password"
  GoogleAnalytics:
    TrackingId: "UA-XXXXXXX-X"
Data:
  PingSettings:
    - ServerUrl: "https://google.com"
      MaxFailures: 3
      GetMethodRequired: false
ServiceManager:
  PingService:
    Enabled: true
    Interval: 30
  DemoService:
    Interval: 5
  DiscrepancyService:
    Interval: 10
    Gaps:
      MaxDifference: 5
Logging:
  MinLogLevel: "Debug"
